# Generated by Django 5.2.1 on 2025-05-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_uz_lot', models.CharField(max_length=100)),
                ('word_uz_kr', models.CharField(max_length=100)),
                ('word_ru', models.CharField(max_length=100)),
                ('word_en', models.CharField(max_length=100)),
                ('word_tu', models.CharField(max_length=100)),
                ('meaning', models.TextField()),
                ('sinon', models.TextField()),
            ],
        ),
    ]
